import {createBowlScene} from './bowl3d.js';

const menu=window.PORKY_MENU, $=s=>document.querySelector(s), money=n=>'Rp'+n.toLocaleString('id-ID');
const bases=menu.filter(p=>['pork','chicken'].includes(p.category)),extras=menu.filter(p=>p.category==='extras');
let selectedBase=bases[0],selectedExtras=[],cart=[],filter='all',sceneAPI=null;
const symbols={e0:'🍚',e1:'🥬',e2:'🍳',e3:'🌶️',e4:'🌿',e5:'🧀'};
let toastTimer;function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2500)}
$('#base').innerHTML=bases.map(p=>`<option value="${p.id}">${p.name} · ${money(p.price)}</option>`).join('');
function buildTotal(){return selectedBase.price+selectedExtras.reduce((s,id)=>s+extras.find(p=>p.id===id).price,0)}
function updateBuilder(){ $('#base-description').textContent=selectedBase.description;$('#build-price').textContent=money(buildTotal());$('#selected-extras').innerHTML=selectedExtras.length?selectedExtras.map((id,i)=>`<button class="chip" data-remove-extra="${i}" aria-label="Remove ${extras.find(p=>p.id===id).name}">${extras.find(p=>p.id===id).name} ×</button>`).join(''):'Your signature, just as it is.';$('#reset-toppings').disabled=!selectedExtras.length; }
function addExtra(id){if(!extras.some(p=>p.id===id))return;if(selectedExtras.length>=18){toast('Maximum 18 extras per bowl. Add another bowl for more.');return}selectedExtras.push(id);updateBuilder();sceneAPI?.addExtra(id,selectedExtras.length-1);toast(extras.find(p=>p.id===id).name+' added to your bowl');}
$('#extras').innerHTML=extras.map(p=>`<button class="extra" draggable="false" data-extra="${p.id}" aria-label="Add ${p.name}, ${money(p.price)}"><span class="symbol" aria-hidden="true"><img src="${p.image}" alt="" draggable="false"></span><strong>${p.name}</strong><small>+ ${money(p.price)}</small><span class="plus">+</span></button>`).join('');
$('#extras').querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.parentElement.textContent=symbols[img.closest('[data-extra]').dataset.extra]},{once:true}));
$('#extras').addEventListener('click',e=>{const b=e.target.closest('[data-extra]');if(b)addExtra(b.dataset.extra)});
const sceneEl=document.querySelector('#scene');
$('#selected-extras').addEventListener('click',e=>{const b=e.target.closest('[data-remove-extra]');if(b){selectedExtras.splice(+b.dataset.removeExtra,1);updateBuilder();sceneAPI?.rebuild()}});
$('#reset-toppings').addEventListener('click',()=>{selectedExtras=[];updateBuilder();sceneAPI?.rebuild();toast('Extra toppings removed')});
$('#base').addEventListener('change',e=>{selectedBase=bases.find(p=>p.id===e.target.value);updateBuilder();sceneAPI?.rebuild()});
function addCart(item){const existing=cart.find(p=>p.key===item.key);if(existing)existing.qty++;else cart.push({...item,qty:1});updateCart();toast('Added to your order ↗')}
$('#add-bowl').addEventListener('click',()=>{const ids=[...selectedExtras].sort();addCart({key:selectedBase.id+':'+ids.join(','),name:selectedBase.name,detail:ids.length?ids.map(id=>extras.find(p=>p.id===id).name).join(' + '):'',price:buildTotal()})});
function updateCart(){const count=cart.reduce((s,p)=>s+p.qty,0),total=cart.reduce((s,p)=>s+p.price*p.qty,0);$('#count').textContent=count;$('#cart-total').textContent=money(total);$('#checkout-button').disabled=!count;$('#cart-items').innerHTML=cart.length?cart.map((p,i)=>`<div class="cart-row"><div><strong>${p.name}</strong>${p.detail?`<small>Extras: ${p.detail}</small>`:''}<small class="row-price">${money(p.price)} / bowl or portion</small></div><div class="qty"><button data-qty="${i}" data-delta="-1" aria-label="Remove one ${p.name}">−</button><span>${p.qty}</span><button data-qty="${i}" data-delta="1" aria-label="Add one ${p.name}">+</button></div><span class="row-price">${money(p.price*p.qty)}</span></div>`).join(''):'<p class="hint">Your next favourite starts with a bowl. Build one, or pick from the menu.</p>';}
$('#cart-items').addEventListener('click',e=>{const b=e.target.closest('[data-qty]');if(!b)return;cart[+b.dataset.qty].qty+=+b.dataset.delta;cart=cart.filter(p=>p.qty>0);updateCart()});
$('.cart-open').addEventListener('click',()=>$('#cart').showModal());$('#cart').addEventListener('click',e=>{if(e.target===$('#cart')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
$('#checkout').addEventListener('submit',e=>{e.preventDefault();if(!cart.length)return;const area=$('#area').value;if(!area){$('#area').reportValidity();return}const total=cart.reduce((s,p)=>s+p.price*p.qty,0);const text=`Halo Porky Brothers! Saya ingin pesan:\n\n${cart.map(p=>`${p.qty}x ${p.name}${p.detail?'\n  Extra: '+p.detail:''}\n  ${money(p.price*p.qty)}`).join('\n')}\n\nSubtotal: ${money(total)}\nArea: ${area}\n${$('#notes').value.trim()?'Catatan: '+$('#notes').value.trim()+'\n':''}\nMohon konfirmasi ketersediaan, ongkir, dan total akhir. Terima kasih!`;window.open('https://wa.me/6285881541029?text='+encodeURIComponent(text),'_blank','noopener,noreferrer')});
const categories={all:'All flavours',pork:'Pork bowls',chicken:'Chicken bowls',meat:'Just the meat',extras:'Extras'};
$('#filters').innerHTML=Object.entries(categories).map(([key,label])=>`<button data-filter="${key}" class="${key==='all'?'active':''}" aria-pressed="${key==='all'}">${label}</button>`).join('');
function renderMenu(){const q=$('#search').value.trim().toLowerCase();const list=menu.filter(p=>(filter==='all'||p.category===filter)&&p.name.toLowerCase().includes(q));$('#menu-grid').innerHTML=list.length?list.map(p=>`<article class="menu-card"><div class="food-image"><img src="${p.image}" data-fallback="${p.originalImage||''}" alt="${p.name} — illustrative food image" loading="lazy">${p.tag?`<span class="tag">${p.tag}</span>`:''}<button data-add="${p.id}" aria-label="Add ${p.name} to order">+</button></div><h3>${p.name}</h3><div class="card-bottom">${money(p.price)}</div></article>`).join(''):'<p class="empty-state">No flavours found. Try another search.</p>';$('#menu-grid').querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{if(img.dataset.fallback){img.src=img.dataset.fallback;img.dataset.fallback=''}},{once:true}))}
$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;$('#filters').querySelectorAll('button').forEach(btn=>{btn.classList.toggle('active',btn===b);btn.setAttribute('aria-pressed',btn===b)});renderMenu()});$('#search').addEventListener('input',renderMenu);$('#menu-grid').addEventListener('click',e=>{const b=e.target.closest('[data-add]');if(b){const p=menu.find(p=>p.id===b.dataset.add);addCart({key:p.id,name:p.name,detail:'',price:p.price})}});
updateBuilder();updateCart();renderMenu();


try{sceneAPI=createBowlScene(sceneEl,()=>selectedBase,()=>selectedExtras);sceneAPI.rebuild()}catch(error){console.warn('3D unavailable',error);const fallback=document.createElement('img');fallback.className='dish-fallback';fallback.alt=selectedBase.name;fallback.src=selectedBase.image;sceneEl.replaceChildren(fallback);document.querySelector('.live').textContent='DISH PREVIEW';sceneAPI={rebuild(){fallback.src=selectedBase.image;fallback.alt=selectedBase.name},addExtra(){}}}


