import * as THREE from './vendor/three.module.js';

export function createBowlScene(element,getBase,getExtras){
 const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.outputColorSpace=THREE.SRGBColorSpace;element.prepend(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,40),bowl=new THREE.Group(),food=new THREE.Group();scene.add(bowl);bowl.add(food);bowl.rotation.y=-.35;
 scene.add(new THREE.HemisphereLight(0xfff3e0,0x343c2e,2.2));const key=new THREE.DirectionalLight(0xffebd5,3.3);key.position.set(-3,7,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-4;key.shadow.camera.right=4;key.shadow.camera.top=4;key.shadow.camera.bottom=-4;key.shadow.normalBias=.025;scene.add(key);const rim=new THREE.DirectionalLight(0xe5eecf,1.5);rim.position.set(4,5,-3);scene.add(rim);
 const materials=[],geometries=[],textures=[];function mat(color,roughness=.6,other={}){const m=new THREE.MeshStandardMaterial({color,roughness,...other});materials.push(m);return m}function geo(g){geometries.push(g);return g}
 let seed=41;const random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};
 function surfaceTexture(base,spots){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d');ctx.fillStyle=base;ctx.fillRect(0,0,256,256);for(let i=0;i<5000;i++){const v=random();ctx.fillStyle=spots[Math.floor(v*spots.length)];ctx.globalAlpha=.2+random()*.6;ctx.beginPath();ctx.ellipse(random()*256,random()*256,.5+random()*3,.3+random()*1.5,random()*6,0,7);ctx.fill()}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;textures.push(t);return t}
 const crustMap=surfaceTexture('#713414',['#2c170a','#b36c2d','#4e210d','#864518','#cc8d44']),leanMap=surfaceTexture('#95603e',['#bc8254','#6a3c24','#d4a776']),fatMap=surfaceTexture('#d6b082',['#f2d5a5','#a97949','#c09562']),sauceMap=surfaceTexture('#702b12',['#a14d1e','#c9773b','#421808']);
 const ceramic=mat(0xe5e0d4,.3),riceMat=mat(0xf2e3c4,.8),lean=mat(0xffffff,.56,{map:leanMap}),fat=mat(0xffffff,.5,{map:fatMap}),crust=mat(0xffffff,.38,{map:crustMap}),braise=mat(0xffffff,.28,{map:sauceMap}),green=mat(0x25481c,.5,{side:THREE.DoubleSide}),greenLight=mat(0x42612a,.57,{side:THREE.DoubleSide}),red=mat(0xb62a14,.36),onion=mat(0xdcb5c1,.42),onionWhite=mat(0xf4dcbe,.44),cheese=mat(0xf3d79a,.48),eggWhite=mat(0xf5e9c5,.48),yolk=mat(0xf3a51b,.3),sesame=mat(0xd8b77b,.75);
 const sphere=geo(new THREE.SphereGeometry(1,16,10)),grain=geo(new THREE.SphereGeometry(1,7,5)),nugget=geo(new THREE.IcosahedronGeometry(1,2));
 // Rounded, slightly irregular meat geometry catches soft highlights on every edge.
 function roundedBox(w,h,d,r){const g=new THREE.BoxGeometry(w,h,d,5,3,5),p=g.attributes.position,v=new THREE.Vector3(),inside=new THREE.Vector3();for(let i=0;i<p.count;i++){v.fromBufferAttribute(p,i);inside.set(THREE.MathUtils.clamp(v.x,-w/2+r,w/2-r),THREE.MathUtils.clamp(v.y,-h/2+r,h/2-r),THREE.MathUtils.clamp(v.z,-d/2+r,d/2-r));v.sub(inside).normalize().multiplyScalar(r).add(inside);p.setXYZ(i,v.x,v.y,v.z)}g.computeVertexNormals();return geo(g)}
 const leanGeo=roundedBox(.49,.19,.38,.06),fatGeo=roundedBox(.50,.075,.385,.032),crustGeo=roundedBox(.51,.09,.39,.035),shred=roundedBox(.035,.025,.23,.01),chilliGeo=roundedBox(.05,.035,.11,.015),onionRing=geo(new THREE.TorusGeometry(.065,.012,5,15,Math.PI*1.6));
 const leafGeo=new THREE.PlaneGeometry(.24,.43,5,7),lp=leafGeo.attributes.position;for(let i=0;i<lp.count;i++){const x=lp.getX(i),y=lp.getY(i),width=Math.sin((y/.43+.5)*Math.PI);lp.setXYZ(i,x*width,y,Math.sin(y*14)*.035+Math.abs(x)*.35)}leafGeo.computeVertexNormals();geo(leafGeo);
 function mesh(g,m,parent=food){const o=new THREE.Mesh(g,m);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 function batches(g,m,count,configure,parent=food){const o=new THREE.InstancedMesh(g,m,count),dummy=new THREE.Object3D();for(let i=0;i<count;i++){dummy.position.set(0,0,0);dummy.rotation.set(0,0,0);dummy.scale.set(1,1,1);configure(dummy,i);dummy.updateMatrix();o.setMatrixAt(i,dummy.matrix)}o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 const profile=[[.02,.04],[.7,.04],[.79,.12],[.82,.2],[1.18,.36],[1.56,.67],[1.83,1.09],[1.98,1.4],[1.97,1.46],[1.89,1.46],[1.79,1.14],[1.49,.74],[1.09,.43],[.7,.29],[.02,.27]].map(p=>new THREE.Vector2(...p));mesh(geo(new THREE.LatheGeometry(profile,100)),ceramic,bowl);const lip=mesh(geo(new THREE.TorusGeometry(1.934,.024,9,100)),mat(0x73805b,.38),bowl);lip.rotation.x=Math.PI/2;lip.position.y=1.454;
 const ground=new THREE.Mesh(geo(new THREE.CircleGeometry(6,70)),new THREE.ShadowMaterial({opacity:.4}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.position.y=.02;scene.add(ground);const orbit=mesh(geo(new THREE.TorusGeometry(2.65,.008,5,100)),mat(0x65734d),scene);orbit.rotation.x=Math.PI/2;orbit.position.y=.025;
 function rice(parent=food,x=0,z=0,y=1.34,r=1.79,n=1700){const mound=mesh(sphere,riceMat,parent);mound.position.set(x,y-.26,z);mound.scale.set(r,.39,r);batches(grain,riceMat,n,(d)=>{const a=random()*Math.PI*2,rad=Math.sqrt(random())*r;d.position.set(x+Math.cos(a)*rad,y+.18*(1-rad*rad/(r*r))+random()*.05,z+Math.sin(a)*rad);d.rotation.set(random()*.5,random()*7,random()*.3);d.scale.set(.021+random()*.012,.021,.054+random()*.02)},parent)}
 function greens(parent,x,z,y,count=72){batches(leafGeo,green,count,d=>{d.position.set(x+(random()-.5)*.9,y+random()*.24,z+(random()-.5)*.7);d.rotation.set(-Math.PI/2+(random()-.5),random()*6,(random()-.5)*.8);d.scale.setScalar(.7+random()*.55)},parent);batches(shred,greenLight,25,d=>{d.position.set(x+(random()-.5)*.65,y+random()*.12,z+(random()-.5)*.5);d.rotation.set(random(),random()*6,random());d.scale.set(.6,.6,1.1)},parent)}
 function sambal(parent,x,z,y,count=95,andaliman=false){batches(onionRing,onion,Math.floor(count*.55),d=>{d.position.set(x+(random()-.5)*.9,y+random()*.15,z+(random()-.5)*.75);d.rotation.set(-Math.PI/2+random()*.7,random(),random()*6);d.scale.set(.7+random()*.8,1+random()*.5,.7)},parent);batches(chilliGeo,andaliman?greenLight:red,Math.floor(count*.5),d=>{d.position.set(x+(random()-.5)*.9,y+random()*.12,z+(random()-.5)*.7);d.rotation.set(random()*.4,random()*6,random()*.4);d.scale.setScalar(.7+random()*.6)},parent);batches(grain,onionWhite,30,d=>{d.position.set(x+(random()-.5)*.8,y+random()*.13,z+(random()-.5)*.6);d.scale.set(.02,.014,.07);d.rotation.y=random()*6},parent)}
 function gratedCheese(parent,x,z,y,n=90){batches(shred,cheese,n,d=>{d.position.set(x+(random()-.5)*1.05,y+random()*.12,z+(random()-.5)*.9);d.rotation.set(random()*.3,random()*6,random()*.3);d.scale.setScalar(.6+random()*.8)},parent)}
 function friedEgg(parent,x,z,y){const white=mesh(sphere,eggWhite,parent);white.position.set(x,y,z);white.scale.set(.47,.07,.38);white.rotation.y=.3;for(let i=0;i<7;i++){const a=i/7*Math.PI*2,w=mesh(sphere,eggWhite,parent);w.position.set(x+Math.cos(a)*.27,y-.01,z+Math.sin(a)*.2);w.scale.set(.24,.05,.17)}const yellow=mesh(sphere,yolk,parent);yellow.position.set(x+.02,y+.08,z);yellow.scale.set(.19,.12,.18)}
 const drops=[];
 function buildMeat(base){const chicken=base.category==='chicken',braised=/Braised|BBQ|Kungpao/.test(base.name),breaded=/Tepung|Fried|Salted|Original|Chicken/.test(base.name),count=chicken?36:30;const positions=[];for(let i=0;i<count;i++){const a=i*2.399,r=1.52*Math.sqrt((i+.5)/count),x=Math.cos(a)*r,z=Math.sin(a)*r;if(x>.75&&z>.25)continue;const g=new THREE.Group();g.position.set(x+(random()-.5)*.15,1.55+.15*(1-r/1.7)+random()*.08,z+(random()-.5)*.15);g.rotation.set((random()-.5)*.42,random()*6,(random()-.5)*.38);g.scale.set(.72+random()*.53,.83+random()*.45,.72+random()*.5);food.add(g);positions.push(g.position.clone());if(chicken||breaded&&base.id!=='p1'&&base.id!=='p2'){const m=mesh(nugget,braised?braise:crust,g);m.scale.set(.27+random()*.06,.15+random()*.05,.23+random()*.05);m.rotation.set(random(),random(),random());const crumb=mesh(nugget,crust,g);crumb.scale.set(.12,.11,.12);crumb.position.set(.14,.03,.08)}else {const leanHeight=.15+random()*.15,fatHeight=.025+random()*.06;const flesh=mesh(leanGeo,braised?braise:lean,g);flesh.scale.y=leanHeight/.19;const f=mesh(fatGeo,fat,g);f.scale.set(.9+random()*.1,fatHeight/.075,.91+random()*.09);f.position.y=leanHeight/2+fatHeight/2;const top=mesh(crustGeo,braised?braise:crust,g);top.position.y=leanHeight/2+fatHeight+.033;top.scale.set(.91+random()*.11,.65+random()*.6,.9+random()*.13);top.rotation.z=(random()-.5)*.09;for(let j=0;j<8;j++){const crackle=mesh(nugget,j%3===0?braise:crust,g);crackle.position.set((random()-.5)*.41,top.position.y+.04,(random()-.5)*.3);crackle.scale.set(.016+random()*.03,.014+random()*.012,.014+random()*.026)}}}
 if(/Mozzarella/.test(base.name))gratedCheese(food,-.35,-.3,1.98,140);if(/Salted Egg/.test(base.name))batches(nugget,yolk,90,d=>{const a=random()*6.28,r=Math.sqrt(random())*1.4;d.position.set(Math.cos(a)*r,1.84+random()*.06,Math.sin(a)*r);d.scale.set(.045,.025,.04)});if(/Kungpao/.test(base.name))batches(chilliGeo,red,50,d=>{d.position.set((random()-.5)*2.5,1.86,(random()-.5)*2.4);d.rotation.y=random()*6;d.scale.set(1.4,1.4,1.8)});return positions.length}
 function clear(){while(food.children.length){const child=food.children[0];food.remove(child);child.traverse(o=>{if(o.isInstancedMesh)o.dispose()})}drops.length=0}
 function rebuild(){clear();seed=41;const base=getBase();rice();const pieces=buildMeat(base);greens(food,1.05,.65,1.54,80);sambal(food,-.68,.82,1.83,110,/Andaliman/.test(base.name));batches(grain,sesame,100,d=>{const a=random()*6.28,r=Math.sqrt(random())*1.45;d.position.set(Math.cos(a)*r,1.94+random()*.03,Math.sin(a)*r);d.rotation.y=random()*6;d.scale.set(.015,.009,.026)});getExtras().forEach((id,index)=>addExtra(id,index,false));element.dataset.meatPieces=String(pieces);element.dataset.extraCount=String(getExtras().length);element.dataset.base=base.id}
 function addExtra(id,index,animate=true){const g=new THREE.Group();food.add(g);const a=index*2.399,r=.45+(index%3)*.25,x=Math.cos(a)*r,z=Math.sin(a)*r,y=1.99+Math.floor(index/6)*.18;g.userData.extra=id;if(id==='e0')rice(g,x,z,y,.65,330);else if(id==='e1')greens(g,x,z,y,80);else if(id==='e2')friedEgg(g,x,z,y);else if(id==='e3'||id==='e4')sambal(g,x,z,y,120,id==='e4');else gratedCheese(g,x,z,y,120);if(animate&&!reduced){g.position.y=1.3;drops.push({g,v:0})}element.dataset.extraCount=String(getExtras().length)}
 let rotation=-.35,tilt=0,pointer=null;const stop=()=>{pointer=null;element.classList.remove('dragging')};element.addEventListener('pointerdown',e=>{if(e.target!==renderer.domElement)return;pointer={x:e.clientX,y:e.clientY,rotation,tilt};element.setPointerCapture(e.pointerId);element.classList.add('dragging')});element.addEventListener('pointermove',e=>{if(pointer){rotation=pointer.rotation+(e.clientX-pointer.x)*.009;tilt=THREE.MathUtils.clamp(pointer.tilt+(e.clientY-pointer.y)*.002,-.12,.22)}});element.addEventListener('pointerup',stop);element.addEventListener('pointercancel',stop);element.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key))return;e.preventDefault();if(e.key==='ArrowLeft')rotation-=.3;if(e.key==='ArrowRight')rotation+=.3;if(e.key==='ArrowUp')tilt=Math.max(-.12,tilt-.04);if(e.key==='ArrowDown')tilt=Math.min(.22,tilt+.04);if(e.key==='Home'){rotation=-.35;tilt=0}});document.querySelector('#rotate-left').onclick=()=>rotation-=.5;document.querySelector('#rotate-right').onclick=()=>rotation+=.5;document.querySelector('#reset-view').onclick=()=>{rotation=-.35;tilt=0};
 function resize(){const w=element.clientWidth,h=element.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.position.set(0,6.7,camera.aspect<1?9.5:7.3);camera.lookAt(0,.9,0);camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(element);resize();let last=performance.now(),nearby=true,running=false;function frame(t){const dt=Math.min((t-last)/1000,.04);last=t;bowl.rotation.y+=(rotation-bowl.rotation.y)*(reduced?1:.14);bowl.rotation.x+=(tilt-bowl.rotation.x)*(reduced?1:.14);for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.v-=dt*13;d.g.position.y+=d.v*dt;if(d.g.position.y<=0){d.g.position.y=0;drops.splice(i,1)}}renderer.render(scene,camera)}function sync(){const active=nearby&&!document.hidden;if(active===running)return;running=active;last=performance.now();renderer.setAnimationLoop(active?frame:null)}document.addEventListener('visibilitychange',sync);new IntersectionObserver(entries=>{nearby=entries[0].isIntersecting;sync()},{rootMargin:'160px'}).observe(element);sync();return{rebuild,addExtra};
}

