'use strict';
const menu=window.PORKY_MENU;
const $=s=>document.querySelector(s);
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
const labels={pork:'pork bowls',chicken:'chicken bowls',meat:'pilihan tanpa nasi',extras:'little extras'};
const cart={};let category='pork',toastTimer,guideTimer,lastGuideText='',lastWaveAt=0;
const mobileGuide=matchMedia('(max-width:720px)');
try{const saved=JSON.parse(localStorage.getItem('porky-playful-cart')||'{}');for(const p of menu)if(Number.isInteger(saved[p.id])&&saved[p.id]>0)cart[p.id]=Math.min(saved[p.id],99)}catch{}
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function photo(p,extra=''){return `<img src="${escapeHTML(p.image)}" data-fallback="${escapeHTML(p.originalImage||'')}" alt="${escapeHTML(p.name)}" ${extra}>`}
function bindImages(){document.querySelectorAll('img[data-fallback]').forEach(img=>{img.onerror=()=>{img.onerror=null;if(img.dataset.fallback)img.src=img.dataset.fallback;else{img.style.objectFit='contain';img.src='../assets/logo.jpeg'}}})}
function stepper(p){return `<div class="stepper"><button type="button" data-change="-1" data-id="${p.id}" aria-label="Kurangi ${escapeHTML(p.name)}">−</button><output aria-label="Jumlah ${escapeHTML(p.name)}">${cart[p.id]}</output><button type="button" data-change="1" data-id="${p.id}" aria-label="Tambah ${escapeHTML(p.name)}" ${cart[p.id]>=99?'disabled':''}>+</button></div>`}
function renderMenu(){const query=$('#search').value.trim().toLowerCase();const shown=menu.filter(p=>query?p.name.toLowerCase().includes(query):p.category===category);$('#result-info').textContent=query?`${shown.length} menu untuk “${$('#search').value.trim()}”`:`${shown.length} ${labels[category]} · pilih, tambah, happy!`;$('#menu-grid').innerHTML=shown.length?shown.map(p=>`<article class="food-card"><div class="food-visual">${photo(p,'loading="lazy" width="700" height="560"')}${p.tag?`<span class="food-tag">${escapeHTML(p.tag)}</span>`:''}</div><div class="food-content"><h3>${escapeHTML(p.name)}</h3><p>${escapeHTML(p.description)}</p><div class="food-bottom"><strong>${money(p.price)}</strong><div class="card-control" data-control="${p.id}">${cart[p.id]?stepper(p):`<button class="add" data-change="1" data-id="${p.id}" aria-label="Tambah ${escapeHTML(p.name)}">Tambah +</button>`}</div></div></div></article>`).join(''):'<p class="no-results">Belum ketemu, nih. Coba nama menu lain, ya!</p>';bindImages()}
function total(){return menu.reduce((n,p)=>n+(cart[p.id]||0)*p.price,0)}
function count(){return Object.values(cart).reduce((n,q)=>n+q,0)}
function renderCart(){const items=menu.filter(p=>cart[p.id]);$('#cart-count').textContent=count();$('#subtotal').textContent=money(total());$('#checkout-button').disabled=!items.length;$('#cart-items').innerHTML=items.length?items.map(p=>`<article class="cart-row">${photo(p,'width="66" height="66"')}<div><h3>${escapeHTML(p.name)}</h3><div class="cart-row-bottom">${stepper(p)}<strong>${money(p.price*cart[p.id])}</strong></div></div></article>`).join(''):'<div class="cart-empty"><strong>Masih kosong, nih!</strong>Happy bowl pertamamu menunggu.<br><button type="button" class="button dark" id="browse-menu" style="margin-top:18px">Yuk, pilih menu ↗</button></div>';bindImages()}
function save(){try{localStorage.setItem('porky-playful-cart',JSON.stringify(cart))}catch{}}
function hideGuide(){clearTimeout(guideTimer);$('#buddy-speech').hidden=true;$('#mascot').setAttribute('aria-expanded','false')}
function scheduleGuideCollapse(){clearTimeout(guideTimer);if(mobileGuide.matches&&!$('#buddy-speech').hidden)guideTimer=setTimeout(hideGuide,5000)}
function speak(text,force=false){if(text===lastGuideText&&!force)return;lastGuideText=text;$('#buddy-speech').innerHTML=`${escapeHTML(text)} <button id="dismiss-buddy" aria-label="Sembunyikan pesan Porky">×</button>`;$('#buddy-speech').hidden=false;$('#mascot').setAttribute('aria-expanded','true');scheduleGuideCollapse();if(force||Date.now()-lastWaveAt>10000){lastWaveAt=Date.now();$('#mascot').classList.remove('wave');requestAnimationFrame(()=>$('#mascot').classList.add('wave'))}}
mobileGuide.addEventListener('change',scheduleGuideCollapse);
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2400)}
function update(id,delta,origin){const p=menu.find(p=>p.id===id);if(!p)return;cart[id]=Math.max(0,Math.min(99,(cart[id]||0)+delta));if(!cart[id])delete cart[id];save();const targetWasCart=origin?.closest('#cart-items');renderMenu();renderCart();const scope=targetWasCart?$('#cart-items'):$('#menu-grid');const replacement=scope.querySelector(`button[data-id="${id}"][data-change="${delta}"]`)||scope.querySelector(`button[data-id="${id}"]`);if(replacement)replacement.focus({preventScroll:true});else if(targetWasCart)($('#cart-items button')||$('#close-cart')).focus({preventScroll:true});if(delta>0){notify(`${p.name} ditambahkan ♥`);if(count()===1)speak('Pilihan bagus! Tambah extra atau cek pesananmu, yuk.')}else if(!count())speak('Mulai lagi? Aku bantu cari favorit barumu!')}
function openCart(){renderCart();$('#cart-dialog').showModal();document.body.classList.add('body-locked');speak(count()?'Tinggal pilih wilayah Jakarta, lalu lanjut ke WhatsApp.':'Pilih menu dulu, yuk!')}
function closeCart(){$('#cart-dialog').close()}
$('#open-cart').addEventListener('click',openCart);$('#close-cart').addEventListener('click',closeCart);$('#cart-dialog').addEventListener('close',()=>document.body.classList.remove('body-locked'));$('#cart-dialog').addEventListener('click',e=>{if(e.target===$('#cart-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeCart()}});
document.addEventListener('click',e=>{const change=e.target.closest('[data-change]');if(change)update(change.dataset.id,Number(change.dataset.change),change);if(e.target.closest('#dismiss-buddy'))hideGuide();if(e.target.closest('#browse-menu')){closeCart();$('#menu').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}});
$('.filters').addEventListener('click',e=>{const button=e.target.closest('[data-category]');if(!button)return;category=button.dataset.category;$('#search').value='';document.querySelectorAll('[data-category]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderMenu()});
$('#search').addEventListener('input',renderMenu);
$('#mascot').addEventListener('click',()=>speak(!count()?'Psst… coba Babi Panggang Sambal Matah. Ini signature kita!':!$('#area').value?'Sudah pilih makanan? Klik Pesananmu, lalu pilih wilayah Jakarta.':'Semua siap! Cek pesananmu lalu lanjut ke WhatsApp.',true));
$('#area').addEventListener('change',()=>{if($('#area').value)speak(`${$('#area').value}, siap! Cek subtotal lalu lanjut ke WhatsApp.`)});
$('#checkout').addEventListener('submit',e=>{e.preventDefault();if(!count()||!$('#checkout').reportValidity())return;const text=['Halo Porky Brothers! Saya ingin pesan:',...menu.filter(p=>cart[p.id]).map(p=>`${cart[p.id]}x ${p.name} @ ${money(p.price)} = ${money(p.price*cart[p.id])}`),'',`Subtotal menu: ${money(total())}`,`Wilayah: ${$('#area').value}`,$('#notes').value.trim()?`Catatan: ${$('#notes').value.trim()}`:'','Mohon konfirmasi ketersediaan, ongkir, dan total pembayaran. Terima kasih!'].filter(Boolean).join('\n');const a=document.createElement('a');a.href=`https://wa.me/6285881541029?text=${encodeURIComponent(text)}`;a.target='_blank';a.rel='noopener noreferrer';a.click();speak('Yay! Kirim pesanmu di WhatsApp untuk konfirmasi pesanan.');notify('Lanjutkan & kirim pesan di WhatsApp ♥')});
renderMenu();renderCart();scheduleGuideCollapse();
