const asset=n=>`../shared/generated/${encodeURIComponent(n)}`;
const menu=[];
function item(id,name,price,category,image,description,tag='',example=false){menu.push({id,name,price,category,image,description,tag,example});}
item('p1','Babi Panggang Sambal Matah',48000,'pork','bowl 1.jpeg','Babi panggang, sambal matah, dan nasi.','THE SIGNATURE');
item('p2','Babi Panggang Sambal Andaliman',50000,'pork','bowl 1.jpeg','Babi panggang dengan sambal andaliman dan nasi.','',true);
item('p3','Braised Pork Belly',48000,'pork','bowl 6.jpeg','Pork belly berbumbu, disajikan dengan nasi.');
item('p4','Fried Pork Sambal Matah',45000,'pork','menu.png','Fried pork, sambal matah, dan nasi.');
item('p5','Babi Tepung Sambal Matah',45000,'pork','bowl 1.jpeg','Babi tepung dengan sambal matah dan nasi.','',true);
item('p6','Original Pork Nasi',45000,'pork','bowl 3.jpeg','Original pork dengan nasi.','',true);
item('p7','BBQ Pork Nasi',45000,'pork','bowl 3.jpeg','Pork dengan saus BBQ dan nasi.','',true);
item('p8','Mozzarella Pork Nasi',45000,'pork','bowl 7.jpeg','Pork, lelehan mozzarella, dan nasi.','CHEESE PLEASE',true);
item('p9','Kungpao Pork Nasi',45000,'pork','bowl 3.jpeg','Pork dengan saus kungpao dan nasi.','',true);
item('p10','Salted Egg Pork Nasi',45000,'pork','menu.png','Salted egg pork, disajikan dengan nasi.');
['Nasi Ayam Chasu Sambal Matah','Original Chicken Rice','BBQ Chicken Rice','Mozzarella Chicken Rice','Kungpao Chicken Rice','Salted Egg Chicken Rice'].forEach((name,i)=>item('c'+i,name,35000,'chicken',i===3?'bowl 7.jpeg':'bowl 4.jpeg','Pilihan rice bowl ayam. Lengkap dengan nasi.',i===1?'CHICKEN FAVOURITE':'',i!==1));
item('m1','Babi Panggang Sambal Matah · 100gr',55000,'meat','Porkbelly.jpeg','Hanya daging, tanpa nasi. Sambal matah.');
item('m2','Babi Panggang Sambal Andaliman · 100gr',58000,'meat','Porkbelly.jpeg','Hanya daging, tanpa nasi. Sambal andaliman.');
item('m3','Braised Pork Belly · Tanpa Nasi',55000,'meat','bowl 6.jpeg','Hanya daging, tanpa nasi.','',true);
['Pork','Chicken'].forEach(protein=>['BBQ','Mozzarella','Original'].forEach(flavour=>[false,true].forEach(jumbo=>item(`m-${protein}-${flavour}-${jumbo}`,`${jumbo?'Jumbo ':''}${flavour} ${protein} · Tanpa Nasi`,protein==='Pork'?(jumbo?60000:45000):(jumbo?50000:40000),'meat',flavour==='Mozzarella'?'bowl 7.jpeg':protein==='Chicken'?'bowl 4.jpeg':'bowl 3.jpeg',`${jumbo?'Porsi jumbo. ':''}Hanya daging, tanpa nasi.`,'',true))));
['Nasi Putih','Sayur Singkong','Telur','Sambal Matah','Sambal Andaliman','Keju Mozzarella'].forEach((name,i)=>item('e'+i,name,i===4?10000:8000,'extras',null,'Tambahan untuk melengkapi pesananmu.'));
for(const p of menu){p.image=p.id+'.png';p.example=false;}
let category='pork';const cart=new Map();const money=n=>'Rp'+n.toLocaleString('id-ID');const $=s=>document.querySelector(s);const total=()=>[...cart].reduce((sum,[id,n])=>sum+menu.find(p=>p.id===id).price*n,0);const count=()=>[...cart.values()].reduce((a,b)=>a+b,0);
function photo(p){return `<img src="${asset(p.image)}" alt="${p.name}" loading="lazy">`;}
function renderProducts(){ $('#products').innerHTML=menu.filter(p=>p.category===category).map(p=>`<article class="product"><div class="product-photo">${photo(p)}${p.tag?`<span class="tag">${p.tag}</span>`:''}${p.example?'<span class="example">Ilustrasi menu sejenis</span>':''}</div><h3>${p.name}</h3><p class="description">${p.description}</p><div class="product-bottom"><span class="price">${money(p.price)}</span><span class="selected-label">${cart.get(p.id)?cart.get(p.id)+' in tray':''}</span><button class="add" data-add="${p.id}" aria-label="Tambah ${p.name}">+</button></div></article>`).join('');}
function renderCart(){let n=count();$('#bag-count').textContent=n;$('#tray-count').textContent=n+' ITEM';$('#total').textContent=money(total());$('#mobile-summary').textContent=n+' item · '+money(total());$('#checkout').disabled=!n;$('#tray-hint').textContent=n?'A little more happiness in every bite.':'Tap + pada menu untuk mengisi tray-mu.';$('#tray').innerHTML=n?[...cart].map(([id,q])=>{const p=menu.find(p=>p.id===id);return p.image&&p.image!=='menu.png'?`<img src="${asset(p.image)}" alt="${q} × ${p.name}" title="${q} × ${p.name}">`:`<span class="extra-chip">${q} × ${p.name}</span>`;}).join(''):'<p>Something delicious<br>belongs here.</p>';$('#cart-items').innerHTML=[...cart].map(([id,q])=>{const p=menu.find(p=>p.id===id);return `<div class="cart-row"><div><strong>${p.name}</strong><span class="line-price">${money(p.price*q)}</span></div><div class="quantity"><button data-remove="${id}" aria-label="Kurangi ${p.name}">−</button><span>${q}</span><button data-add="${id}" aria-label="Tambah ${p.name}" ${q>=99?'disabled':''}>+</button></div></div>`;}).join('');}
let toastTimer;function add(id){const p=menu.find(p=>p.id===id);if(!p|| (cart.get(id)||0)>=99)return;cart.set(id,(cart.get(id)||0)+1);renderProducts();renderCart();$('#toast').textContent=p.name+' added to your tray';$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2000);}
document.addEventListener('click',e=>{const plus=e.target.closest('[data-add]');if(plus)add(plus.dataset.add);const minus=e.target.closest('[data-remove]');if(minus){const id=minus.dataset.remove,q=cart.get(id);if(q>1)cart.set(id,q-1);else cart.delete(id);renderProducts();renderCart();}const tab=e.target.closest('[data-category]');if(tab){category=tab.dataset.category;document.querySelectorAll('[data-category]').forEach(b=>{b.classList.toggle('active',b===tab);b.setAttribute('aria-pressed',b===tab);});$('#category-note').textContent={pork:'Pork favourites, lengkap dengan nasi.',chicken:'Chicken favourites, semua Rp35.000.',meat:'Hanya daging, tanpa nasi. Pilih rasa dan porsi favoritmu.',extras:'A little extra untuk melengkapi pesananmu.'}[category];renderProducts();}});
function orderMessage(){return ['Halo Porky Brothers! Saya mau pesan:', '',...[...cart].map(([id,q])=>{const p=menu.find(p=>p.id===id);return `${q}x ${p.name} — ${money(p.price*q)}`;}),'',`Subtotal: ${money(total())}`,`Area pengiriman: ${$('#area').value}`,...($('#notes').value.trim()?[`Catatan: ${$('#notes').value.trim()}`]:[]),'','Mohon konfirmasi ketersediaan, ongkir, total akhir, dan cara pembayaran non-tunai. Terima kasih!'].join('\n');}
$('#order-form').addEventListener('submit',e=>{e.preventDefault();if(!count()||!$('#order-form').reportValidity())return;const a=document.createElement('a');a.href='https://wa.me/6285881541029?text='+encodeURIComponent(orderMessage());a.target='_blank';a.rel='noopener noreferrer';a.click();});renderProducts();renderCart();
