window.PORKY_MENU = [
  {
    "id": "p1",
    "name": "Babi Panggang Sambal Matah",
    "price": 48000,
    "category": "pork",
    "image": "../shared/generated/p1.png",
    "description": "Babi panggang, sambal matah, dan nasi.",
    "tag": "THE SIGNATURE",
    "example": false,
    "originalImage": "../assets/bowl%201.jpeg",
    "generated": true
  },
  {
    "id": "p2",
    "name": "Babi Panggang Sambal Andaliman",
    "price": 50000,
    "category": "pork",
    "image": "../shared/generated/p2.png",
    "description": "Babi panggang dengan sambal andaliman dan nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%201.jpeg",
    "generated": true
  },
  {
    "id": "p3",
    "name": "Braised Pork Belly",
    "price": 48000,
    "category": "pork",
    "image": "../shared/generated/p3.png",
    "description": "Pork belly berbumbu, disajikan dengan nasi.",
    "tag": "",
    "example": false,
    "originalImage": "../assets/bowl%206.jpeg",
    "generated": true
  },
  {
    "id": "p4",
    "name": "Fried Pork Sambal Matah",
    "price": 45000,
    "category": "pork",
    "image": "../shared/generated/p4.png",
    "description": "Fried pork, sambal matah, dan nasi.",
    "tag": "",
    "example": false,
    "originalImage": "../assets/menu.png",
    "generated": true
  },
  {
    "id": "p5",
    "name": "Babi Tepung Sambal Matah",
    "price": 45000,
    "category": "pork",
    "image": "../shared/generated/p5.png",
    "description": "Babi tepung dengan sambal matah dan nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%201.jpeg",
    "generated": true
  },
  {
    "id": "p6",
    "name": "Original Pork Nasi",
    "price": 45000,
    "category": "pork",
    "image": "../shared/generated/p6.png",
    "description": "Original pork dengan nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%203.jpeg",
    "generated": true
  },
  {
    "id": "p7",
    "name": "BBQ Pork Nasi",
    "price": 45000,
    "category": "pork",
    "image": "../shared/generated/p7.png",
    "description": "Pork dengan saus BBQ dan nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%203.jpeg",
    "generated": true
  },
  {
    "id": "p8",
    "name": "Mozzarella Pork Nasi",
    "price": 45000,
    "category": "pork",
    "image": "../shared/generated/p8.png",
    "description": "Pork, lelehan mozzarella, dan nasi.",
    "tag": "CHEESE PLEASE",
    "example": true,
    "originalImage": "../assets/bowl%207.jpeg",
    "generated": true
  },
  {
    "id": "p9",
    "name": "Kungpao Pork Nasi",
    "price": 45000,
    "category": "pork",
    "image": "../shared/generated/p9.png",
    "description": "Pork dengan saus kungpao dan nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%203.jpeg",
    "generated": true
  },
  {
    "id": "p10",
    "name": "Salted Egg Pork Nasi",
    "price": 45000,
    "category": "pork",
    "image": "../shared/generated/p10.png",
    "description": "Salted egg pork, disajikan dengan nasi.",
    "tag": "",
    "example": false,
    "originalImage": "../assets/menu.png",
    "generated": true
  },
  {
    "id": "c0",
    "name": "Nasi Ayam Chasu Sambal Matah",
    "price": 35000,
    "category": "chicken",
    "image": "../shared/generated/c0.png",
    "description": "Pilihan rice bowl ayam. Lengkap dengan nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%204.jpeg",
    "generated": true
  },
  {
    "id": "c1",
    "name": "Original Chicken Rice",
    "price": 35000,
    "category": "chicken",
    "image": "../shared/generated/c1.png",
    "description": "Pilihan rice bowl ayam. Lengkap dengan nasi.",
    "tag": "CHICKEN FAVOURITE",
    "example": false,
    "originalImage": "../assets/bowl%204.jpeg",
    "generated": true
  },
  {
    "id": "c2",
    "name": "BBQ Chicken Rice",
    "price": 35000,
    "category": "chicken",
    "image": "../shared/generated/c2.png",
    "description": "Pilihan rice bowl ayam. Lengkap dengan nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%204.jpeg",
    "generated": true
  },
  {
    "id": "c3",
    "name": "Mozzarella Chicken Rice",
    "price": 35000,
    "category": "chicken",
    "image": "../shared/generated/c3.png",
    "description": "Pilihan rice bowl ayam. Lengkap dengan nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%207.jpeg",
    "generated": true
  },
  {
    "id": "c4",
    "name": "Kungpao Chicken Rice",
    "price": 35000,
    "category": "chicken",
    "image": "../shared/generated/c4.png",
    "description": "Pilihan rice bowl ayam. Lengkap dengan nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%204.jpeg",
    "generated": true
  },
  {
    "id": "c5",
    "name": "Salted Egg Chicken Rice",
    "price": 35000,
    "category": "chicken",
    "image": "../shared/generated/c5.png",
    "description": "Pilihan rice bowl ayam. Lengkap dengan nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%204.jpeg",
    "generated": true
  },
  {
    "id": "m1",
    "name": "Babi Panggang Sambal Matah · 100gr",
    "price": 55000,
    "category": "meat",
    "image": "../shared/generated/m1.png",
    "description": "Hanya daging, tanpa nasi. Sambal matah.",
    "tag": "",
    "example": false,
    "originalImage": "../assets/Porkbelly.jpeg",
    "generated": true
  },
  {
    "id": "m2",
    "name": "Babi Panggang Sambal Andaliman · 100gr",
    "price": 58000,
    "category": "meat",
    "image": "../shared/generated/m2.png",
    "description": "Hanya daging, tanpa nasi. Sambal andaliman.",
    "tag": "",
    "example": false,
    "originalImage": "../assets/Porkbelly.jpeg",
    "generated": true
  },
  {
    "id": "m3",
    "name": "Braised Pork Belly · Tanpa Nasi",
    "price": 55000,
    "category": "meat",
    "image": "../shared/generated/m3.png",
    "description": "Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%206.jpeg",
    "generated": true
  },
  {
    "id": "m-Pork-BBQ-false",
    "name": "BBQ Pork · Tanpa Nasi",
    "price": 45000,
    "category": "meat",
    "image": "../shared/generated/m-Pork-BBQ-false.png",
    "description": "Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%203.jpeg",
    "generated": true
  },
  {
    "id": "m-Pork-BBQ-true",
    "name": "Jumbo BBQ Pork · Tanpa Nasi",
    "price": 60000,
    "category": "meat",
    "image": "../shared/generated/m-Pork-BBQ-true.png",
    "description": "Porsi jumbo. Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%203.jpeg",
    "generated": true
  },
  {
    "id": "m-Pork-Mozzarella-false",
    "name": "Mozzarella Pork · Tanpa Nasi",
    "price": 45000,
    "category": "meat",
    "image": "../shared/generated/m-Pork-Mozzarella-false.png",
    "description": "Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%207.jpeg",
    "generated": true
  },
  {
    "id": "m-Pork-Mozzarella-true",
    "name": "Jumbo Mozzarella Pork · Tanpa Nasi",
    "price": 60000,
    "category": "meat",
    "image": "../shared/generated/m-Pork-Mozzarella-true.png",
    "description": "Porsi jumbo. Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%207.jpeg",
    "generated": true
  },
  {
    "id": "m-Pork-Original-false",
    "name": "Original Pork · Tanpa Nasi",
    "price": 45000,
    "category": "meat",
    "image": "../shared/generated/m-Pork-Original-false.png",
    "description": "Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%203.jpeg",
    "generated": true
  },
  {
    "id": "m-Pork-Original-true",
    "name": "Jumbo Original Pork · Tanpa Nasi",
    "price": 60000,
    "category": "meat",
    "image": "../shared/generated/m-Pork-Original-true.png",
    "description": "Porsi jumbo. Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%203.jpeg",
    "generated": true
  },
  {
    "id": "m-Chicken-BBQ-false",
    "name": "BBQ Chicken · Tanpa Nasi",
    "price": 40000,
    "category": "meat",
    "image": "../shared/generated/m-Chicken-BBQ-false.png",
    "description": "Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%204.jpeg",
    "generated": true
  },
  {
    "id": "m-Chicken-BBQ-true",
    "name": "Jumbo BBQ Chicken · Tanpa Nasi",
    "price": 50000,
    "category": "meat",
    "image": "../shared/generated/m-Chicken-BBQ-true.png",
    "description": "Porsi jumbo. Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%204.jpeg",
    "generated": true
  },
  {
    "id": "m-Chicken-Mozzarella-false",
    "name": "Mozzarella Chicken · Tanpa Nasi",
    "price": 40000,
    "category": "meat",
    "image": "../shared/generated/m-Chicken-Mozzarella-false.png",
    "description": "Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%207.jpeg",
    "generated": true
  },
  {
    "id": "m-Chicken-Mozzarella-true",
    "name": "Jumbo Mozzarella Chicken · Tanpa Nasi",
    "price": 50000,
    "category": "meat",
    "image": "../shared/generated/m-Chicken-Mozzarella-true.png",
    "description": "Porsi jumbo. Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%207.jpeg",
    "generated": true
  },
  {
    "id": "m-Chicken-Original-false",
    "name": "Original Chicken · Tanpa Nasi",
    "price": 40000,
    "category": "meat",
    "image": "../shared/generated/m-Chicken-Original-false.png",
    "description": "Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%204.jpeg",
    "generated": true
  },
  {
    "id": "m-Chicken-Original-true",
    "name": "Jumbo Original Chicken · Tanpa Nasi",
    "price": 50000,
    "category": "meat",
    "image": "../shared/generated/m-Chicken-Original-true.png",
    "description": "Porsi jumbo. Hanya daging, tanpa nasi.",
    "tag": "",
    "example": true,
    "originalImage": "../assets/bowl%204.jpeg",
    "generated": true
  },
  {
    "id": "e0",
    "name": "Nasi Putih",
    "price": 8000,
    "category": "extras",
    "image": "../shared/generated/e0.png",
    "description": "Tambahan untuk melengkapi pesananmu.",
    "tag": "",
    "example": false,
    "originalImage": null,
    "generated": true
  },
  {
    "id": "e1",
    "name": "Sayur Singkong",
    "price": 8000,
    "category": "extras",
    "image": "../shared/generated/e1.png",
    "description": "Tambahan untuk melengkapi pesananmu.",
    "tag": "",
    "example": false,
    "originalImage": null,
    "generated": true
  },
  {
    "id": "e2",
    "name": "Telur",
    "price": 8000,
    "category": "extras",
    "image": "../shared/generated/e2.png",
    "description": "Tambahan untuk melengkapi pesananmu.",
    "tag": "",
    "example": false,
    "originalImage": null,
    "generated": true
  },
  {
    "id": "e3",
    "name": "Sambal Matah",
    "price": 8000,
    "category": "extras",
    "image": "../shared/generated/e3.png",
    "description": "Tambahan untuk melengkapi pesananmu.",
    "tag": "",
    "example": false,
    "originalImage": null,
    "generated": true
  },
  {
    "id": "e4",
    "name": "Sambal Andaliman",
    "price": 10000,
    "category": "extras",
    "image": "../shared/generated/e4.png",
    "description": "Tambahan untuk melengkapi pesananmu.",
    "tag": "",
    "example": false,
    "originalImage": null,
    "generated": true
  },
  {
    "id": "e5",
    "name": "Keju Mozzarella",
    "price": 8000,
    "category": "extras",
    "image": "../shared/generated/e5.png",
    "description": "Tambahan untuk melengkapi pesananmu.",
    "tag": "",
    "example": false,
    "originalImage": null,
    "generated": true
  }
];